### ISSUE TITLE
Exception Saving entity NBT 

### ISSUE THREAD

**Issue by cesartl** [AdityaGupta1/minecraft-catapult#10]
After spawning a catapult I got the following exception in the logs:

```
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.writeToNBT(Entity.java:1553) ~[Entity.class:?]
	at net.minecraft.entity.Entity.writeToNBTOptional(Entity.java:1489) ~[Entity.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.writeChunkToNBT(AnvilChunkLoader.java:371) [AnvilChunkLoader.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.saveChunk(AnvilChunkLoader.java:204) [AnvilChunkLoader.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.safeSaveChunk(ChunkProviderServer.java:287) [ChunkProviderServer.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.saveChunks(ChunkProviderServer.java:340) [ChunkProviderServer.class:?]
	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:863) [WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:370) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:113) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.entity.EntityLivingBase.writeEntityToNBT(EntityLivingBase.java:481) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.EntityLiving.writeEntityToNBT(EntityLiving.java:313) ~[EntityLiving.class:?]
	at net.minecraft.entity.EntityAgeable.writeEntityToNBT(EntityAgeable.java:119) ~[EntityAgeable.class:?]
	at net.minecraft.entity.passive.EntityAnimal.writeEntityToNBT(EntityAnimal.java:242) ~[EntityAnimal.class:?]
	at net.minecraft.entity.Entity.writeToNBT(Entity.java:1536) ~[Entity.class:?]

```

**Comment by cesartl** [comment]
duplicate of issue #9
