### ISSUE TITLE
Crash on tab-completing /catapult command

### ISSUE THREAD

**Issue by AdityaGupta1** [AdityaGupta1/minecraft-catapult#14]
```
net.minecraft.util.ReportedException: Ticking memory connection
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:198) ~[NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.command.CommandBase.doesStringStartWith(CommandBase.java:495) ~[CommandBase.class:?]
	at net.minecraft.command.CommandHandler.getPossibleCommands(CommandHandler.java:197) ~[CommandHandler.class:?]
	at net.minecraft.server.MinecraftServer.getPossibleCompletions(MinecraftServer.java:887) ~[MinecraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processTabComplete(NetHandlerPlayServer.java:1143) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.C14PacketTabComplete.processPacket(C14PacketTabComplete.java:43) ~[C14PacketTabComplete.class:?]
	at net.minecraft.network.play.client.C14PacketTabComplete.processPacket(C14PacketTabComplete.java:64) ~[C14PacketTabComplete.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241) ~[NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182) ~[NetworkSystem.class:?]
	... 5 more
[23:32:04] [Server thread/ERROR]: This crash report has been saved to: /Users/Aditya/Programming/minecraft-catapult/eclipse/./crash-reports/crash-2017-06-22_23.32.04-server.txt
[23:32:04] [Server thread/INFO]: Stopping server
[23:32:04] [Server thread/INFO]: Saving players
[23:32:04] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:388]: ---- Minecraft Crash Report ----
// There are four lights!

Time: 6/22/17 11:32 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at net.minecraft.command.CommandBase.doesStringStartWith(CommandBase.java:495)
	at net.minecraft.command.CommandHandler.getPossibleCommands(CommandHandler.java:197)
	at net.minecraft.server.MinecraftServer.getPossibleCompletions(MinecraftServer.java:887)
	at net.minecraft.network.NetHandlerPlayServer.processTabComplete(NetHandlerPlayServer.java:1143)
	at net.minecraft.network.play.client.C14PacketTabComplete.processPacket(C14PacketTabComplete.java:43)
	at net.minecraft.network.play.client.C14PacketTabComplete.processPacket(C14PacketTabComplete.java:64)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.command.CommandBase.doesStringStartWith(CommandBase.java:495)
	at net.minecraft.command.CommandHandler.getPossibleCommands(CommandHandler.java:197)
	at net.minecraft.server.MinecraftServer.getPossibleCompletions(MinecraftServer.java:887)
	at net.minecraft.network.NetHandlerPlayServer.processTabComplete(NetHandlerPlayServer.java:1143)
	at net.minecraft.network.play.client.C14PacketTabComplete.processPacket(C14PacketTabComplete.java:43)
	at net.minecraft.network.play.client.C14PacketTabComplete.processPacket(C14PacketTabComplete.java:64)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1ef2ad66
Stacktrace:
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

```

**Comment by AdityaGupta1** [comment]
Seems to happen on tab-completing any command

Tested with `/gamerule`

**Comment by AdityaGupta1** [comment]
Does not happen with arguments, such as `/gamerule doDaylightCycle`

**Comment by AdityaGupta1** [comment]
Probably not related to method `addTabCompletionOptions(ICommandSender sender, String[] args)` of `ICommand`, but it may be worth a look

**Comment by cesartl** [comment]
perhaps 
```
@Override
	public List addTabCompletionOptions(ICommandSender p_71516_1_, String[] p_71516_2_) {
		return null;
	}
```
should return `Collections.emptyList()` rather than `null`

**Comment by AdityaGupta1** [comment]
Just tried that, doesn't work
